[build-system]
requires = ["setuptools", "wheel", "cython"]
build-backend = "setuptools.build_meta"      # path to build backend object

[tool.black]
line-length = 120
target-version = ["py39", "py310"]